### ISSUE TITLE
Clear code, variable names and functions 

### ISSUE THREAD

**Issue by rosie-ollerenshaw** [fac21/Week-8-MM-Quiz#17]
https://github.com/fac21/Week-8-MM-Quiz/blob/53b76f1e0c1849bcee46a22c7b3a47f0067393bc/src/components/QuizData.jsx#L33

We are really impressed with your code :) I really loved reading through it and working out what you were doing - we found it easy to read through and understand what was happening, which we think is due to really good naming of variables and functions :)

**Comment by maryamgh1988** [comment]
wow thanks alot
