### ISSUE TITLE
Mentor Code Review - Wow!!!

### ISSUE THREAD

**Issue by fairyaksh** [fac21/Week-8-MM-Quiz#19]
Firstly, a huge well done on coming this far in your React app! There's some really amazing logic and cool ideas being sprinkled throughout your project so keep up the creativity and hard work!

1. Don't forget to catch errors when you're fetching from an API - it will save a lot of time when you're debugging the data being returned or any other errors as you start to populate your UI with the API data. Referring to file QuizData.jsx

2. General note to remember to remove any comments (e.g. in QuizData.jsx, App.jsx). While it's excellent to see you're all writing pseudocode and other comments to help track your logic, it'll make the code cleaner if they were removed!

3. Really nice start to your readme. Could make it even more extensive by adding things like how to setup and run your project locally, which dependencies you added on top of existing ones (if any), your design process and any figma/design prototypes, etc etc. [This](https://www.freecodecamp.org/news/how-to-write-a-good-readme-file/) is a good reference.

4. Try to keep things that aren't code in a 'public' folder - so it would look like `src/public/images/image1.png`

5. In your App.css, you have an empty p tag! Make sure you check all your css files are clean as well as your JS/JSX.

6. Not 100% sure what the `workspace.code-workspace` file is doing or why ? Curious to know 😺 

7. Might be nitpicky given time constraint and priority of learning/understanding React over styling but try to add some more responsiveness to your project in the future! It's also just nice idea to take a break from the taxing React logic and make things pretty, especially if/when you're having some tough bugs to hack!!

8. Just want to highlight how clean and clear nearly all of your code is! I could understand quite easily what the purpose of the functions were due to the great naming conventions and code structure ⭐ 

Succccchhh a good project in just 2 days!!! and I believe your hard work has really paid off this week, so please give yourself more credit and feel very proud of yourself 😍

**Comment by maryamgh1988** [comment]
Thanks
